staffmod:
  vanish:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: EYE_OF_ENDER
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "§eVanish"
        lore:
          - "§eClick to §aenable §eor §cdisable §ethe vanish."
    slot: 0
  freeze:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: BLAZE_ROD
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "§eFreeze"
        lore:
          - "§eClick to §afreeze §eor §cunfreeze §ea player."
    slot: 1
  invsee:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: CHEST
      amount: 1
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: "§eInvsee"
        lore:
          - "§eClick on a §6player §eto see his inventory."
    slot: 2