name: ConfigurableStaffModExample
author: Syrows
version: 1.0.0
main: fr.syrows.configurablestaffmodexample.ConfigurableStaffModExample
commands:
  configurablestaffmod:
    description: "A command used to enable or disable a configurable staff mod."